{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: {{ $service.namespace }}
data:
  DB_HOST: "terraform-platform-test-terraform-platform-test-db.c9o0iwiqig5w.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "tenantcrm"
---
{{- end }}
