apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: v1
kind: Namespace
metadata:
  name: admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: employee
---
apiVersion: v1
kind: Namespace
metadata:
  name: customer
---
apiVersion: v1
kind: Namespace
metadata:
  name: hr
---
apiVersion: v1
kind: Namespace
metadata:
  name: task
